export type Screen =
  | 'splash'
  | 'login'
  | 'register'
  | 'otp'
  | 'identity'
  | 'pending'
  | 'dashboard'
  | 'dashboard-offline'
  | 'jobs'
  | 'jobs-empty'
  | 'delivery-request'
  | 'pickup-nav'
  | 'customer-nav'
  | 'active-tracking'
  | 'delivery-complete'
  | 'earnings'
  | 'history'
  | 'history-loading'
  | 'history-error'
  | 'notifications'
  | 'profile'
  | 'settings'

export type NavFn = (s: Screen) => void
